# Generated by Django 5.2.5 on 2025-08-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the blog post and Open Graph preview.', null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Optimal length: 150-160 characters', max_length=160),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optimal length: 50-60 characters', max_length=60),
        ),
        migrations.AddField(
            model_name='post',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description. If blank, uses meta description.', max_length=160),
        ),
        migrations.AddField(
            model_name='post',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title. If blank, uses meta title or post title.', max_length=60),
        ),
    ]
